// Native OS menu (DDR-106 Task 6). Built from the action registry's generated native slice,
// `menu.actions.json` (scripts/gen-actions.mjs — Maude v2 V2-1.3 §5.8, V2-2.4 step 6): the
// registry names each item, its label and its accelerator; this file only turns the slice into
// Tauri menu items. Never add an item here by hand — add it to apps/studio/actions/native-menu.ts
// (+ the action in defs/) and regenerate.

use serde::Deserialize;
use tauri::menu::{AboutMetadataBuilder, Menu, MenuBuilder, MenuItemBuilder, SubmenuBuilder};
use tauri::{AppHandle, Runtime};

/// Menu-item id for the File ▸ New Project… action.
pub const MENU_NEW_PROJECT: &str = "new_project";

/// Menu-item id for the File ▸ Open Project… action.
pub const MENU_OPEN_PROJECT: &str = "open_project";

/// Menu-item id for the Maude ▸ Check for Updates… action (manual update check).
pub const MENU_CHECK_UPDATES: &str = "check_updates";

/// Menu-item id for the Help ▸ Report a Bug… action (feature-bug-report-button).
pub const MENU_REPORT_BUG: &str = "report_bug";

/// Every item id lib.rs's `on_menu_event` has an arm for. The slice may name no other. Test-only:
/// lib.rs matches the `MENU_*` constants directly, so keep this list in step with its arms.
#[cfg(test)]
pub const HANDLED_MENU_IDS: [&str; 4] = [
    MENU_NEW_PROJECT,
    MENU_OPEN_PROJECT,
    MENU_CHECK_UPDATES,
    MENU_REPORT_BUG,
];

/// The generated slice, embedded at compile time.
const MENU_ACTIONS_JSON: &str = include_str!("../menu.actions.json");

#[derive(Debug, Deserialize)]
struct MenuSpec {
    menus: Vec<SubmenuSpec>,
}

#[derive(Debug, Deserialize)]
struct SubmenuSpec {
    title: String,
    items: Vec<ItemSpec>,
}

#[derive(Debug, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
enum ItemSpec {
    /// A registry action: `id` is the menu-item id lib.rs matches on.
    Item {
        id: String,
        label: String,
        #[serde(default)]
        accel: Option<String>,
    },
    /// An OS-provided item (About, Quit, the Edit items WKWebView needs).
    Predefined {
        name: String,
        #[serde(default)]
        macos: bool,
    },
    Separator {
        #[serde(default)]
        macos: bool,
    },
}

fn spec() -> MenuSpec {
    serde_json::from_str(MENU_ACTIONS_JSON)
        .expect("menu.actions.json is generated by scripts/gen-actions.mjs and parses")
}

/// Build the application menu. The first submenu becomes the macOS app menu.
pub fn build_menu<R: Runtime>(app: &AppHandle<R>) -> tauri::Result<Menu<R>> {
    let mut submenus = Vec::new();
    for menu in spec().menus {
        let mut b = SubmenuBuilder::new(app, &menu.title);
        for item in menu.items {
            b = match item {
                ItemSpec::Item { id, label, accel } => {
                    let mut it = MenuItemBuilder::with_id(id, label);
                    if let Some(accel) = accel {
                        it = it.accelerator(accel);
                    }
                    b.item(&it.build(app)?)
                }
                // Undo / Redo (and the separator after them) are macOS-only — unsupported on
                // Windows / Linux.
                ItemSpec::Predefined { macos: true, .. } | ItemSpec::Separator { macos: true }
                    if !cfg!(target_os = "macos") =>
                {
                    b
                }
                ItemSpec::Predefined { name, .. } => match name.as_str() {
                    "about" => b.about(Some(
                        AboutMetadataBuilder::new()
                            .name(Some("Maude"))
                            .version(Some(env!("CARGO_PKG_VERSION")))
                            .build(),
                    )),
                    "quit" => b.quit(),
                    "undo" => b.undo(),
                    "redo" => b.redo(),
                    "cut" => b.cut(),
                    "copy" => b.copy(),
                    "paste" => b.paste(),
                    "select_all" => b.select_all(),
                    other => panic!("menu.actions.json: unknown predefined item `{other}`"),
                },
                ItemSpec::Separator { .. } => b.separator(),
            };
        }
        submenus.push(b.build()?);
    }
    let refs: Vec<&dyn tauri::menu::IsMenuItem<R>> = submenus
        .iter()
        .map(|s| s as &dyn tauri::menu::IsMenuItem<R>)
        .collect();
    MenuBuilder::new(app).items(&refs).build()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn items() -> Vec<(String, String, Option<String>)> {
        spec()
            .menus
            .into_iter()
            .flat_map(|m| {
                let title = m.title;
                m.items.into_iter().filter_map(move |i| match i {
                    ItemSpec::Item { id, accel, .. } => Some((title.clone(), id, accel)),
                    _ => None,
                })
            })
            .collect()
    }

    #[test]
    fn menu_actions_every_item_has_a_handler_arm() {
        for (_, id, _) in items() {
            assert!(
                HANDLED_MENU_IDS.contains(&id.as_str()),
                "menu.actions.json item `{id}` has no arm in lib.rs on_menu_event"
            );
        }
        let ids: Vec<String> = items().into_iter().map(|(_, id, _)| id).collect();
        for handled in HANDLED_MENU_IDS {
            assert!(
                ids.iter().any(|i| i == handled),
                "handled id `{handled}` is not in the menu"
            );
        }
    }

    #[test]
    fn menu_actions_keep_the_v1_menu() {
        // V2-2.4 is a pure swap: same submenus, same items, same accelerators as the hand-built
        // menu it replaced.
        let titles: Vec<String> = spec().menus.into_iter().map(|m| m.title).collect();
        assert_eq!(titles, ["Maude", "File", "Edit", "Help"]);
        assert_eq!(
            items(),
            vec![
                ("Maude".into(), "check_updates".into(), None),
                (
                    "File".into(),
                    "new_project".into(),
                    Some("CmdOrCtrl+N".into())
                ),
                (
                    "File".into(),
                    "open_project".into(),
                    Some("CmdOrCtrl+O".into())
                ),
                ("Help".into(), "report_bug".into(), None),
            ]
        );
    }
}
