// GENERATED by scripts/gen-actions.mjs from apps/studio/actions/ — DO NOT EDIT BY HAND.
// Run: node scripts/gen-actions.mjs (CI runs it with --check). The canvas iframe's slim key
// table (V2-1.3 §5.7): every binding the canvas document resolves, without labels or docs, so the
// canvas bundle never needs the whole registry and never waits for a keymap push.
import type { KeyedAction } from './types.ts';

export const CANVAS_KEYMAP: readonly KeyedAction[] = [
  {
    id: 'search.open',
    exec: 'shell',
    fromCanvas: true,
    keys: [{ chord: '⌘K', layer: 'global', inText: true }],
  },
  {
    id: 'canvas.reload',
    exec: 'shell',
    fromCanvas: true,
    keys: [{ chord: '⌘R', layer: 'global', inText: true }],
  },
  {
    id: 'edit.undo',
    exec: 'canvas',
    keys: [{ chord: '⌘Z', layer: 'global', when: { focus: ['canvas'] } }],
  },
  {
    id: 'edit.redo',
    exec: 'canvas',
    keys: [
      { chord: '⇧⌘Z', layer: 'global', when: { focus: ['canvas'] } },
      { chord: '⌘Y', layer: 'global', alias: true, when: { focus: ['canvas'] } },
    ],
  },
  {
    id: 'select.all',
    exec: 'canvas',
    keys: [
      { chord: '⌘A', layer: 'selection', when: { focus: ['canvas'] } },
      { chord: '⇧⌘A', layer: 'selection', when: { focus: ['canvas'] }, alias: true },
    ],
  },
  {
    id: 'object.duplicate',
    exec: 'canvas',
    keys: [{ chord: '⌘D', layer: 'selection', when: { focus: ['canvas'], selection: ['object'] } }],
  },
  {
    id: 'edit.copy-properties',
    exec: 'canvas',
    keys: [
      { chord: '⌥⌘C', layer: 'selection', when: { focus: ['canvas'], selection: ['object'] } },
      {
        chord: '⌥⇧⌘C',
        layer: 'selection',
        when: { focus: ['canvas'], selection: ['object'] },
        alias: true,
      },
    ],
  },
  {
    id: 'edit.paste-properties',
    exec: 'canvas',
    keys: [
      { chord: '⌥⌘V', layer: 'selection', when: { focus: ['canvas'], selection: ['object'] } },
      {
        chord: '⌥⇧⌘V',
        layer: 'selection',
        when: { focus: ['canvas'], selection: ['object'] },
        alias: true,
      },
    ],
  },
  {
    id: 'object.select-child',
    exec: 'canvas',
    keys: [{ chord: '↵', layer: 'selection', when: { focus: ['canvas'], selection: ['object'] } }],
  },
  {
    id: 'object.select-parent',
    exec: 'canvas',
    keys: [{ chord: '⇧↵', layer: 'selection', when: { focus: ['canvas'], selection: ['object'] } }],
  },
  {
    id: 'object.select-next',
    exec: 'canvas',
    keys: [
      { chord: 'tab', layer: 'selection', when: { focus: ['canvas'], selection: ['object'] } },
      { chord: '⇧tab', layer: 'selection', when: { focus: ['canvas'], selection: ['object'] } },
    ],
  },
  {
    id: 'object.remove',
    exec: 'canvas',
    keys: [
      {
        chord: '⌫',
        layer: 'selection',
        when: { focus: ['canvas'], selection: ['object', 'artboard'] },
      },
      {
        chord: '⇧⌫',
        layer: 'selection',
        when: { focus: ['canvas'], selection: ['object', 'artboard'] },
        alias: true,
      },
      {
        chord: '⌦',
        layer: 'selection',
        when: { focus: ['canvas'], selection: ['object', 'artboard'] },
      },
      {
        chord: '⇧⌦',
        layer: 'selection',
        when: { focus: ['canvas'], selection: ['object', 'artboard'] },
        alias: true,
      },
    ],
  },
  {
    id: 'object.nudge',
    exec: 'canvas',
    keys: [
      {
        chord: '←',
        layer: 'selection',
        when: { focus: ['canvas'], selection: ['object', 'artboard'] },
      },
      {
        chord: '⇧←',
        layer: 'selection',
        when: { focus: ['canvas'], selection: ['object', 'artboard'] },
        alias: true,
      },
      {
        chord: '→',
        layer: 'selection',
        when: { focus: ['canvas'], selection: ['object', 'artboard'] },
      },
      {
        chord: '⇧→',
        layer: 'selection',
        when: { focus: ['canvas'], selection: ['object', 'artboard'] },
        alias: true,
      },
      {
        chord: '↑',
        layer: 'selection',
        when: { focus: ['canvas'], selection: ['object', 'artboard'] },
      },
      {
        chord: '⇧↑',
        layer: 'selection',
        when: { focus: ['canvas'], selection: ['object', 'artboard'] },
        alias: true,
      },
      {
        chord: '↓',
        layer: 'selection',
        when: { focus: ['canvas'], selection: ['object', 'artboard'] },
      },
      {
        chord: '⇧↓',
        layer: 'selection',
        when: { focus: ['canvas'], selection: ['object', 'artboard'] },
        alias: true,
      },
    ],
  },
  {
    id: 'view.comments',
    exec: 'shell',
    fromCanvas: true,
    keys: [{ chord: '⇧⌘M', layer: 'global', inText: true }],
  },
  {
    id: 'history.open',
    exec: 'shell',
    fromCanvas: true,
    keys: [{ chord: '⇧⌘G', layer: 'global', inText: true }],
  },
  {
    id: 'view.inspector',
    exec: 'shell',
    fromCanvas: true,
    keys: [{ chord: '⇧⌘I', layer: 'global', inText: true }],
  },
  {
    id: 'view.timeline-keep-open',
    exec: 'shell',
    fromCanvas: true,
    keys: [{ chord: '⇧⌘T', layer: 'global', inText: true }],
  },
  {
    id: 'view.annotations',
    exec: 'canvas',
    keys: [{ chord: '⇧P', layer: 'global', inText: false, when: { focus: ['canvas'] } }],
  },
  {
    id: 'view.zoom-in',
    exec: 'canvas',
    keys: [
      { chord: '⌘=', layer: 'global', inText: true, when: { focus: ['canvas', 'text'] } },
      {
        chord: '⌘+',
        layer: 'global',
        inText: true,
        alias: true,
        when: { focus: ['canvas', 'text'] },
      },
    ],
  },
  {
    id: 'view.zoom-out',
    exec: 'canvas',
    keys: [{ chord: '⌘−', layer: 'global', inText: true, when: { focus: ['canvas', 'text'] } }],
  },
  {
    id: 'view.zoom-fit',
    exec: 'canvas',
    keys: [{ chord: '⌘0', layer: 'global', inText: true, when: { focus: ['canvas', 'text'] } }],
  },
  {
    id: 'view.zoom-actual',
    exec: 'canvas',
    keys: [{ chord: '⌘1', layer: 'global', inText: true, when: { focus: ['canvas', 'text'] } }],
  },
  {
    id: 'view.jump-artboard',
    exec: 'canvas',
    keys: [
      {
        chord: '⌥⌘1',
        layer: 'global',
        inText: true,
        alias: false,
        when: { focus: ['canvas', 'text'] },
      },
      {
        chord: '⌥⌘2',
        layer: 'global',
        inText: true,
        alias: true,
        when: { focus: ['canvas', 'text'] },
      },
      {
        chord: '⌥⌘3',
        layer: 'global',
        inText: true,
        alias: true,
        when: { focus: ['canvas', 'text'] },
      },
      {
        chord: '⌥⌘4',
        layer: 'global',
        inText: true,
        alias: true,
        when: { focus: ['canvas', 'text'] },
      },
      {
        chord: '⌥⌘5',
        layer: 'global',
        inText: true,
        alias: true,
        when: { focus: ['canvas', 'text'] },
      },
      {
        chord: '⌥⌘6',
        layer: 'global',
        inText: true,
        alias: true,
        when: { focus: ['canvas', 'text'] },
      },
      {
        chord: '⌥⌘7',
        layer: 'global',
        inText: true,
        alias: true,
        when: { focus: ['canvas', 'text'] },
      },
      {
        chord: '⌥⌘8',
        layer: 'global',
        inText: true,
        alias: true,
        when: { focus: ['canvas', 'text'] },
      },
      {
        chord: '⌥⌘9',
        layer: 'global',
        inText: true,
        alias: true,
        when: { focus: ['canvas', 'text'] },
      },
    ],
  },
  {
    id: 'tool.select',
    exec: 'canvas',
    keys: [
      { chord: 'V', layer: 'tools', when: { focus: ['canvas'] } },
      { chord: '⇧V', layer: 'tools', when: { focus: ['canvas'] }, alias: true },
    ],
  },
  {
    id: 'tool.hand',
    exec: 'canvas',
    keys: [
      { chord: 'H', layer: 'tools', when: { focus: ['canvas'] } },
      { chord: '⇧H', layer: 'tools', when: { focus: ['canvas'] }, alias: true },
    ],
  },
  {
    id: 'tool.hand-hold',
    exec: 'canvas',
    keys: [
      { chord: 'Space', layer: 'tools', hold: true, when: { focus: ['canvas'] } },
      { chord: '⌥Space', layer: 'tools', hold: true, when: { focus: ['canvas'] }, alias: true },
      { chord: '⇧Space', layer: 'tools', hold: true, when: { focus: ['canvas'] }, alias: true },
      { chord: '⌥⇧Space', layer: 'tools', hold: true, when: { focus: ['canvas'] }, alias: true },
      { chord: '⌘Space', layer: 'tools', hold: true, when: { focus: ['canvas'] }, alias: true },
      { chord: '⌥⌘Space', layer: 'tools', hold: true, when: { focus: ['canvas'] }, alias: true },
      { chord: '⇧⌘Space', layer: 'tools', hold: true, when: { focus: ['canvas'] }, alias: true },
      { chord: '⌥⇧⌘Space', layer: 'tools', hold: true, when: { focus: ['canvas'] }, alias: true },
    ],
  },
  {
    id: 'tool.comment',
    exec: 'canvas',
    keys: [
      { chord: 'C', layer: 'tools', when: { focus: ['canvas'] } },
      { chord: '⇧C', layer: 'tools', when: { focus: ['canvas'] }, alias: true },
    ],
  },
  {
    id: 'tool.pen',
    exec: 'canvas',
    keys: [
      { chord: 'B', layer: 'tools', when: { focus: ['canvas'] } },
      { chord: '⇧B', layer: 'tools', when: { focus: ['canvas'] }, alias: true },
    ],
  },
  {
    id: 'tool.highlighter',
    exec: 'canvas',
    keys: [
      { chord: 'I', layer: 'tools', when: { focus: ['canvas'] } },
      { chord: '⇧I', layer: 'tools', when: { focus: ['canvas'] }, alias: true },
    ],
  },
  {
    id: 'tool.shape',
    exec: 'canvas',
    keys: [
      { chord: 'R', layer: 'tools', when: { focus: ['canvas'] } },
      { chord: '⇧R', layer: 'tools', when: { focus: ['canvas'] }, alias: true },
      { chord: 'O', layer: 'tools', when: { focus: ['canvas'] }, alias: true },
      { chord: '⇧O', layer: 'tools', when: { focus: ['canvas'] }, alias: true },
    ],
  },
  {
    id: 'tool.arrow',
    exec: 'canvas',
    keys: [
      { chord: 'A', layer: 'tools', when: { focus: ['canvas'] } },
      { chord: '⇧A', layer: 'tools', when: { focus: ['canvas'] }, alias: true },
    ],
  },
  {
    id: 'tool.sticky',
    exec: 'canvas',
    keys: [
      { chord: 'N', layer: 'tools', when: { focus: ['canvas'] } },
      { chord: '⇧N', layer: 'tools', when: { focus: ['canvas'] }, alias: true },
    ],
  },
  {
    id: 'tool.text',
    exec: 'canvas',
    keys: [
      { chord: 'T', layer: 'tools', when: { focus: ['canvas'] } },
      { chord: '⇧T', layer: 'tools', when: { focus: ['canvas'] }, alias: true },
    ],
  },
  {
    id: 'tool.section',
    exec: 'canvas',
    keys: [{ chord: '⇧S', layer: 'tools', when: { focus: ['canvas'] } }],
  },
  {
    id: 'tool.eraser',
    exec: 'canvas',
    keys: [
      { chord: 'E', layer: 'tools', when: { focus: ['canvas'] } },
      { chord: '⇧E', layer: 'tools', when: { focus: ['canvas'] }, alias: true },
    ],
  },
  {
    id: 'ui.step-back',
    exec: 'shell',
    keys: [
      { chord: 'esc', layer: 'selection', inText: false, when: { focus: ['canvas'] } },
      {
        chord: '⌥esc',
        layer: 'selection',
        inText: false,
        when: { focus: ['canvas'] },
        alias: true,
      },
      {
        chord: '⇧esc',
        layer: 'selection',
        inText: false,
        when: { focus: ['canvas'] },
        alias: true,
      },
      {
        chord: '⌥⇧esc',
        layer: 'selection',
        inText: false,
        when: { focus: ['canvas'] },
        alias: true,
      },
      {
        chord: '⌘esc',
        layer: 'selection',
        inText: false,
        when: { focus: ['canvas'] },
        alias: true,
      },
      {
        chord: '⌥⌘esc',
        layer: 'selection',
        inText: false,
        when: { focus: ['canvas'] },
        alias: true,
      },
      {
        chord: '⇧⌘esc',
        layer: 'selection',
        inText: false,
        when: { focus: ['canvas'] },
        alias: true,
      },
      {
        chord: '⌥⇧⌘esc',
        layer: 'selection',
        inText: false,
        when: { focus: ['canvas'] },
        alias: true,
      },
    ],
  },
  {
    id: 'export.open',
    exec: 'shell',
    fromCanvas: true,
    keys: [{ chord: '⇧⌘E', layer: 'global', inText: true }],
  },
  {
    id: 'handoff.open',
    exec: 'shell',
    fromCanvas: true,
    keys: [{ chord: '⇧⌘H', layer: 'global', inText: true }],
  },
  {
    id: 'export.canvas-dialog',
    exec: 'canvas',
    keys: [{ chord: '⌘E', layer: 'tools', inText: true, when: { focus: ['canvas', 'text'] } }],
  },
  {
    id: 'export.rerun-last',
    exec: 'canvas',
    keys: [{ chord: '⇧⌘E', layer: 'tools', inText: true, when: { focus: ['canvas', 'text'] } }],
  },
  {
    id: 'annotation.group',
    exec: 'canvas',
    keys: [
      { chord: '⌘G', layer: 'selection', when: { focus: ['canvas'], selection: ['annotation'] } },
    ],
  },
  {
    id: 'annotation.ungroup',
    exec: 'canvas',
    keys: [
      { chord: '⇧⌘G', layer: 'selection', when: { focus: ['canvas'], selection: ['annotation'] } },
    ],
  },
  {
    id: 'annotation.lock',
    exec: 'canvas',
    keys: [
      { chord: '⇧⌘L', layer: 'selection', when: { focus: ['canvas'], selection: ['annotation'] } },
    ],
  },
  {
    id: 'annotation.duplicate',
    exec: 'canvas',
    keys: [
      { chord: '⌘D', layer: 'selection', when: { focus: ['canvas'], selection: ['annotation'] } },
    ],
  },
  {
    id: 'annotation.to-front',
    exec: 'canvas',
    keys: [
      { chord: ']', layer: 'selection', when: { focus: ['canvas'], selection: ['annotation'] } },
    ],
  },
  {
    id: 'annotation.forward',
    exec: 'canvas',
    keys: [
      { chord: '⌘]', layer: 'selection', when: { focus: ['canvas'], selection: ['annotation'] } },
    ],
  },
  {
    id: 'annotation.to-back',
    exec: 'canvas',
    keys: [
      { chord: '[', layer: 'selection', when: { focus: ['canvas'], selection: ['annotation'] } },
    ],
  },
  {
    id: 'annotation.backward',
    exec: 'canvas',
    keys: [
      { chord: '⌘[', layer: 'selection', when: { focus: ['canvas'], selection: ['annotation'] } },
    ],
  },
  {
    id: 'annotation.copy',
    exec: 'canvas',
    keys: [
      { chord: '⌘C', layer: 'selection', when: { focus: ['canvas'], selection: ['annotation'] } },
    ],
  },
  {
    id: 'annotation.cut',
    exec: 'canvas',
    keys: [
      { chord: '⌘X', layer: 'selection', when: { focus: ['canvas'], selection: ['annotation'] } },
    ],
  },
  {
    id: 'annotation.chain',
    exec: 'canvas',
    keys: [
      { chord: '⌘↵', layer: 'selection', when: { focus: ['canvas'], selection: ['annotation'] } },
    ],
  },
  {
    id: 'annotation.edit-text',
    exec: 'canvas',
    keys: [
      { chord: '↵', layer: 'selection', when: { focus: ['canvas'], selection: ['annotation'] } },
    ],
  },
  {
    id: 'annotation.nudge',
    exec: 'canvas',
    keys: [
      { chord: '←', layer: 'selection', when: { focus: ['canvas'], selection: ['annotation'] } },
      {
        chord: '⇧←',
        layer: 'selection',
        when: { focus: ['canvas'], selection: ['annotation'] },
        alias: true,
      },
      { chord: '→', layer: 'selection', when: { focus: ['canvas'], selection: ['annotation'] } },
      {
        chord: '⇧→',
        layer: 'selection',
        when: { focus: ['canvas'], selection: ['annotation'] },
        alias: true,
      },
      { chord: '↑', layer: 'selection', when: { focus: ['canvas'], selection: ['annotation'] } },
      {
        chord: '⇧↑',
        layer: 'selection',
        when: { focus: ['canvas'], selection: ['annotation'] },
        alias: true,
      },
      { chord: '↓', layer: 'selection', when: { focus: ['canvas'], selection: ['annotation'] } },
      {
        chord: '⇧↓',
        layer: 'selection',
        when: { focus: ['canvas'], selection: ['annotation'] },
        alias: true,
      },
    ],
  },
  {
    id: 'annotation.remove',
    exec: 'canvas',
    keys: [
      { chord: '⌫', layer: 'selection', when: { focus: ['canvas'], selection: ['annotation'] } },
      {
        chord: '⇧⌫',
        layer: 'selection',
        when: { focus: ['canvas'], selection: ['annotation'] },
        alias: true,
      },
      { chord: '⌦', layer: 'selection', when: { focus: ['canvas'], selection: ['annotation'] } },
      {
        chord: '⇧⌦',
        layer: 'selection',
        when: { focus: ['canvas'], selection: ['annotation'] },
        alias: true,
      },
    ],
  },
];
