/* _components.css — shared component anatomy (Phase 3.6.1 emit-conditionally).
 *
 * This file is OPTIONAL. The bootstrap scaffolder emits it when Q9 signature
 * treatment ≠ `none` AND the treatment repeats across 3+ components — at that
 * point promoting class anatomy out of per-specimen <style> blocks reduces
 * drift and makes critic-panel scans cleaner.
 *
 * Project-specific component classes (.btn / .tile / .input / etc.) are
 * authored by the scaffolder for the specific Q9 family. The MOTION ROLE
 * CLASSES below are the universally-shared piece — they ship verbatim
 * regardless of Q9 family, because the motion vocabulary is fixed at 8 roles
 * per DDR-049.
 */

/* ─────────────────────────────────────────────────────────────────────── */
/* Schema v1 class contract (V2-1.13 §5.3.9 / §5.3.11) — structure only: every value is a
 * Tier-1 token, a keyword, 0 or a 1px hairline (DDR-043). Restyle freely by editing the token
 * values or adding rules below; keep the class names — canvases and `@maude/ds` rely on them. */
/* ds-schema:components:begin — GENERATED by scripts/gen-ds-schema.mjs, do not edit */
/* Button */
.btn { display: inline-flex; align-items: center; justify-content: center; gap: var(--space-2); padding: var(--space-2) var(--space-4); border: 1px solid transparent; border-radius: var(--radius-md); font: var(--weight-medium) var(--type-sm) / var(--lh-sm) var(--font-body); color: var(--fg-0); background: var(--bg-3); cursor: pointer; }
.btn:hover { background: var(--bg-4); }
.btn:focus-visible { outline: var(--focus-ring-width) solid var(--focus-ring); outline-offset: var(--focus-ring-offset); }
.btn:disabled { color: var(--fg-3); cursor: not-allowed; }
.btn[aria-pressed="true"] { background: var(--accent-soft); color: var(--accent-on-soft); }
.btn[aria-busy="true"] { cursor: progress; }
.btn--primary { background: var(--accent); color: var(--accent-fg); }
.btn--primary:hover { background: var(--accent-hover); }
.btn--primary:active { background: var(--accent-active); }
.btn--secondary { background: var(--bg-1); border-color: var(--border-default); }
.btn--ghost { background: transparent; }
.btn--danger { background: var(--status-error); color: var(--status-error-fg); }
.btn--sm { padding: var(--space-1) var(--space-3); font-size: var(--type-xs); }
.btn--lg { padding: var(--space-3) var(--space-5); font-size: var(--type-base); }

/* IconButton */
.btn--icon { padding: var(--space-2); }

/* Input */
.input, .textarea, .select { font: var(--weight-regular) var(--type-sm) / var(--lh-sm) var(--font-body); color: var(--fg-0); background: var(--bg-3); border: 1px solid var(--border-default); border-radius: var(--radius-md); padding: var(--space-2) var(--space-3); }
.input:focus-visible, .textarea:focus-visible, .select:focus-visible { outline: var(--focus-ring-width) solid var(--focus-ring); outline-offset: var(--focus-ring-offset); }
.input:disabled, .textarea:disabled, .select:disabled { color: var(--fg-3); }
.input[aria-invalid="true"], .textarea[aria-invalid="true"], .select[aria-invalid="true"] { border-color: var(--status-error); }
.input--sm { padding: var(--space-1) var(--space-2); font-size: var(--type-xs); }

/* Field */
.field { display: flex; flex-direction: column; gap: var(--space-1); }
.field__label { font: var(--weight-medium) var(--type-sm) / var(--lh-sm) var(--font-body); color: var(--fg-1); }
.field__hint { font: var(--weight-regular) var(--type-xs) / var(--lh-xs) var(--font-body); color: var(--fg-2); }
.field__error { font: var(--weight-regular) var(--type-xs) / var(--lh-xs) var(--font-body); color: var(--status-error-text); }

/* Switch */
.switch { appearance: none; display: inline-flex; align-items: center; padding: var(--space-1); border: 0; border-radius: var(--radius-pill); background: var(--bg-4); cursor: pointer; }
.switch::after { content: ""; display: block; width: var(--space-4); height: var(--space-4); border-radius: var(--radius-pill); background: var(--bg-1); box-shadow: var(--shadow-sm); }
.switch[aria-checked="true"] { background: var(--accent); justify-content: flex-end; }
.switch:disabled { cursor: not-allowed; }
.switch:focus-visible { outline: var(--focus-ring-width) solid var(--focus-ring); outline-offset: var(--focus-ring-offset); }

/* Checkbox */
.checkbox, .radio { accent-color: var(--accent); }
.checkbox:focus-visible, .radio:focus-visible { outline: var(--focus-ring-width) solid var(--focus-ring); outline-offset: var(--focus-ring-offset); }

/* Segmented */
.seg { display: inline-flex; gap: var(--space-1); padding: var(--space-1); background: var(--bg-3); border-radius: var(--radius-md); }
.seg__item { font: var(--weight-medium) var(--type-sm) / var(--lh-sm) var(--font-body); padding: var(--space-1) var(--space-3); border: 0; border-radius: var(--radius-sm); background: transparent; color: var(--fg-1); cursor: pointer; }
.seg__item[aria-pressed="true"], .seg__item[aria-selected="true"] { background: var(--bg-1); color: var(--fg-0); box-shadow: var(--shadow-sm); }
.seg--sm .seg__item { font-size: var(--type-xs); }

/* Tabs */
.tabs { display: flex; gap: var(--space-4); border-bottom: 1px solid var(--border-subtle); }
.tab { font: var(--weight-medium) var(--type-sm) / var(--lh-sm) var(--font-body); padding: var(--space-2) 0; border: 0; border-bottom: 1px solid transparent; background: transparent; color: var(--fg-1); cursor: pointer; }
.tab[aria-selected="true"] { color: var(--accent-text); border-bottom-color: var(--accent); }

/* Chip */
.chip { display: inline-flex; align-items: center; gap: var(--space-1); padding: 0 var(--space-2); border-radius: var(--radius-pill); background: var(--bg-3); color: var(--fg-1); font: var(--weight-medium) var(--type-xs) / var(--lh-xs) var(--font-body); }
.chip--accent { background: var(--accent); color: var(--accent-fg); }
.chip--soft, .chip[aria-pressed="true"] { background: var(--accent-soft); color: var(--accent-on-soft); }
.chip:focus-visible { outline: var(--focus-ring-width) solid var(--focus-ring); outline-offset: var(--focus-ring-offset); }

/* Badge */
.badge { display: inline-flex; align-items: center; padding: 0 var(--space-2); border-radius: var(--radius-sm); background: var(--bg-3); color: var(--fg-1); font: var(--weight-semibold) var(--type-xs) / var(--lh-xs) var(--font-body); }
.badge--success { background: var(--status-success-soft); color: var(--status-success-text); }
.badge--warn { background: var(--status-warn-soft); color: var(--status-warn-text); }
.badge--error { background: var(--status-error-soft); color: var(--status-error-text); }
.badge--info { background: var(--status-info-soft); color: var(--status-info-text); }
.badge--accent { background: var(--accent-soft); color: var(--accent-on-soft); }

/* Card */
.card { background: var(--bg-1); color: var(--fg-0); border: 1px solid var(--border-subtle); border-radius: var(--radius-lg); padding: var(--space-4); }
.card--raised { box-shadow: var(--shadow-md); }
.card--flat { border-color: transparent; }
.card--interactive { cursor: pointer; }
.card--interactive:hover { border-color: var(--border-default); }
.card--interactive:focus-visible { outline: var(--focus-ring-width) solid var(--focus-ring); outline-offset: var(--focus-ring-offset); }

/* Callout */
.callout { display: flex; gap: var(--space-3); padding: var(--space-3) var(--space-4); border: 1px solid var(--border-subtle); border-radius: var(--radius-md); background: var(--bg-2); color: var(--fg-0); font: var(--weight-regular) var(--type-sm) / var(--lh-sm) var(--font-body); }
.callout--info { background: var(--status-info-soft); border-color: var(--status-info); }
.callout--success { background: var(--status-success-soft); border-color: var(--status-success); }
.callout--warn { background: var(--status-warn-soft); border-color: var(--status-warn); }
.callout--error { background: var(--status-error-soft); border-color: var(--status-error); }

/* Dialog */
.dialog { display: flex; flex-direction: column; gap: var(--space-4); padding: var(--space-5); background: var(--bg-2); color: var(--fg-0); border: 1px solid var(--border-subtle); border-radius: var(--radius-xl); box-shadow: var(--shadow-lg); }
.dialog__title { font: var(--weight-semibold) var(--type-xl) / var(--lh-xl) var(--font-display); letter-spacing: var(--tracking-tight); margin: 0; }
.dialog__body { font: var(--weight-regular) var(--type-base) / var(--lh-base) var(--font-body); color: var(--fg-1); }
.dialog__actions { display: flex; justify-content: flex-end; gap: var(--space-2); }
.scrim { position: fixed; inset: 0; background: var(--scrim); }

/* Tooltip */
.tooltip { padding: var(--space-1) var(--space-2); border-radius: var(--radius-sm); background: var(--fg-0); color: var(--bg-0); box-shadow: var(--shadow-md); font: var(--weight-medium) var(--type-xs) / var(--lh-xs) var(--font-body); }

/* Type roles (<Text role>) */
.t-title { font-family: var(--font-display); font-size: var(--type-2xl); line-height: var(--lh-2xl); font-weight: var(--weight-semibold); letter-spacing: var(--tracking-tight); }
.t-heading { font-family: var(--font-display); font-size: var(--type-xl); line-height: var(--lh-xl); font-weight: var(--weight-semibold); letter-spacing: var(--tracking-tight); }
.t-subheading { font-family: var(--font-body); font-size: var(--type-lg); line-height: var(--lh-lg); font-weight: var(--weight-medium); letter-spacing: var(--tracking-normal); }
.t-body { font-family: var(--font-body); font-size: var(--type-base); line-height: var(--lh-base); font-weight: var(--weight-regular); letter-spacing: var(--tracking-normal); }
.t-body-sm { font-family: var(--font-body); font-size: var(--type-sm); line-height: var(--lh-sm); font-weight: var(--weight-regular); letter-spacing: var(--tracking-normal); }
.t-caption { font-family: var(--font-body); font-size: var(--type-xs); line-height: var(--lh-xs); font-weight: var(--weight-regular); letter-spacing: var(--tracking-normal); }
.t-label { font-family: var(--font-body); font-size: var(--type-sm); line-height: var(--lh-sm); font-weight: var(--weight-medium); letter-spacing: var(--tracking-normal); }
.t-eyebrow { font-family: var(--font-body); font-size: var(--type-xs); line-height: var(--lh-xs); font-weight: var(--weight-semibold); letter-spacing: var(--tracking-wide); }
.t-code { font-family: var(--font-mono); font-size: var(--type-sm); line-height: var(--lh-sm); font-weight: var(--weight-regular); letter-spacing: 0; }
.t-num { font-variant-numeric: tabular-nums; }
/* ds-schema:components:end */

/* ─────────────────────────────────────────────────────────────────────── */
/* Motion role classes — CSS-only escape hatch for the canvas-lib motion
 * vocabulary (Phase 3.7 / DDR-049). Use when a canvas wants the role
 * vocabulary without importing motion/react. The shape MUST stay in sync
 * with `<MotionDemo role>` in canvas-lib.tsx.
 *
 * Usage:  <div className="motion-flip">…</div>
 *         <div className="motion-soft">…</div>
 *
 * Each class is `animation: <kf> <dur> <ease> infinite alternate` so the
 * element loops on first paint (matching the canvas-lib helper's default
 * loop="always"). To opt out of the loop, set `animation-iteration-count: 1`
 * on the host or use `animation-play-state: paused`.
 *
 * Reduced-motion is enforced by the colors_and_type.css token collapse
 * (--dur-*: 1ms under prefers-reduced-motion: reduce) — these classes
 * inherit that for free.
 */

/* flip — press-down, hover lift. */
@keyframes motion-flip-kf {
  0% { transform: translateY(0); }
  100% { transform: translateY(-12px); }
}
.motion-flip {
  animation: motion-flip-kf var(--dur-flip, 220ms) var(--ease-out, ease-out) infinite alternate;
  overflow: hidden;
}

/* panel — drawer / sidebar slide. */
@keyframes motion-panel-kf {
  0% { transform: translateX(-80px); }
  100% { transform: translateX(0); }
}
.motion-panel {
  animation: motion-panel-kf var(--dur-panel, 320ms) var(--ease-in-out, ease-in-out) infinite alternate;
  overflow: hidden;
}

/* route — page transition (opacity + tiny scale). */
@keyframes motion-route-kf {
  0% { opacity: 0; transform: scale(0.92); }
  100% { opacity: 1; transform: scale(1); }
}
.motion-route {
  animation: motion-route-kf var(--dur-route, 480ms) var(--ease-out, ease-out) infinite alternate;
  overflow: hidden;
}

/* soft — toast / tooltip / soft reveal. */
@keyframes motion-soft-kf {
  0% { opacity: 0; }
  100% { opacity: 1; }
}
.motion-soft {
  animation: motion-soft-kf var(--dur-soft, 160ms) var(--ease-out, ease-out) infinite alternate;
}

/* spring — tactile/playful settle. CSS spring approximation only — for
 * production spring fidelity, lift <MotionDemo role="spring" /> instead. */
@keyframes motion-spring-kf {
  0% { transform: translateY(0); }
  60% { transform: translateY(-20px); }
  78% { transform: translateY(-12px); }
  90% { transform: translateY(-16px); }
  100% { transform: translateY(-14px); }
}
.motion-spring {
  animation: motion-spring-kf var(--dur-panel, 320ms) cubic-bezier(0.34, 1.56, 0.64, 1) infinite alternate;
  overflow: hidden;
}

/* scroll — scroll-progress-bound entry. CSS-only fallback; real scroll-link
 * needs JS (motion/react useScroll). */
@keyframes motion-scroll-kf {
  0% { transform: translateX(0); }
  100% { transform: translateX(24px); }
}
.motion-scroll {
  animation: motion-scroll-kf var(--dur-route, 480ms) var(--ease-in-out, ease-in-out) infinite alternate;
  overflow: hidden;
}

/* drag — pick-up + release rotational settle. CSS-only fallback. */
@keyframes motion-drag-kf {
  0% { transform: rotate(0); }
  50% { transform: rotate(4deg); }
  100% { transform: rotate(0); }
}
.motion-drag {
  animation: motion-drag-kf var(--dur-flip, 220ms) var(--ease-out, ease-out) infinite alternate;
  overflow: hidden;
}

/* presence — sparkle / pulse. Demo on ≤56px elements ONLY (bounded geometry —
 * a full-width tile pulsing scale: 0→1 will overflow adjacent rows). */
@keyframes motion-presence-kf {
  0% { opacity: 0; transform: scale(0.9); }
  100% { opacity: 1; transform: scale(1); }
}
.motion-presence {
  animation: motion-presence-kf var(--dur-soft, 160ms) var(--ease-out, ease-out) infinite alternate;
  overflow: hidden;
  /* Bounded-geometry guard — the class is intended for elements ≤56px.
   * Sites that violate this earn a motion-critic blocker. */
  max-width: 56px;
  max-height: 56px;
}

/* Honor explicit data-reduced-motion toggle (specimen chrome) AND the
 * standing OS-level prefers-reduced-motion (the token collapse already
 * neutralises the durations; the JS-set attribute is for inspection symmetry). */
:root[data-reduced-motion="true"] [class*="motion-"] {
  animation: none !important;
}
