// GENERATED by scripts/gen-tokens.mjs from .design/system/maude/colors_and_type.css
// — DO NOT EDIT BY HAND. Run: node scripts/gen-tokens.mjs
// The canvas iframe's HUD/chrome token block (--maude-hud-*, --maude-chrome-*), injected by
// canvas-shell.tsx. See the comment above its import there for why the HUD owns its own family.
export const HUD_TOKENS_CSS = `
:root,
:root[data-maude-theme="dark"] {
  --maude-hud-accent:        oklch(0.680 0.180 268);
  --maude-hud-accent-hover:  oklch(0.730 0.170 268);
  --maude-hud-accent-active: oklch(0.630 0.180 268);
  --maude-hud-accent-fg:     oklch(0.180 0.030 268);
  --maude-hud-accent-tint:   color-mix(in oklab, oklch(0.680 0.180 268) 16%, transparent);

  --maude-chrome-bg-0:      oklch(0.165 0.012 255);
  --maude-chrome-bg-1:      oklch(0.198 0.012 255);
  --maude-chrome-bg-2:      oklch(0.232 0.013 255);
  --maude-chrome-fg-0:      oklch(0.955 0.005 250);
  --maude-chrome-fg-1:      oklch(0.790 0.008 250);
  --maude-chrome-border:    oklch(0.290 0.012 255);
  --maude-chrome-dot:       oklch(0.340 0.012 255);
  --maude-chrome-shadow:    rgba(0, 0, 0, 0.46);
  --maude-chrome-font-mono: 'JetBrains Mono', 'Geist Mono', ui-monospace, 'SF Mono', Menlo, monospace;
}
:root[data-maude-theme="light"] {
  --maude-hud-accent:        oklch(0.520 0.195 268);
  --maude-hud-accent-hover:  oklch(0.470 0.195 268);
  --maude-hud-accent-active: oklch(0.430 0.190 268);
  --maude-hud-accent-fg:     oklch(0.995 0.004 268);
  --maude-hud-accent-tint:   color-mix(in oklab, oklch(0.520 0.195 268) 12%, transparent);

  --maude-chrome-bg-0:   oklch(0.975 0.004 255);
  --maude-chrome-bg-1:   oklch(1.000 0 0);
  --maude-chrome-bg-2:   oklch(0.987 0.003 255);
  --maude-chrome-fg-0:   oklch(0.225 0.015 260);
  --maude-chrome-fg-1:   oklch(0.400 0.014 260);
  --maude-chrome-border: oklch(0.922 0.005 255);
  --maude-chrome-dot:    oklch(0.860 0.008 255);
  --maude-chrome-shadow: color-mix(in oklab, oklch(0.225 0.015 260) 14%, transparent);
}
`;
