// The fallback layer (V2-1.13 §5.5) — ONE generator for both outputs:
//   renderFallbacks(registry)            → schema/ds-schema-v1.fallbacks.css (everything)
//   renderFallbacks(registry, declared)  → the shell's per-system block (only what the system
//                                          never declares, so it can never shadow a system value)
//
// Invariants F1–F6: declared on every theme wrapper; only undeclared names / classes; inside
// `@layer maude.fallback` (lowest — unlayered system CSS always wins); no visual prior (colours
// derive from the system's own tokens, weights are CSS numeric weights, tracking 0, focus 2px);
// no inversion for single-theme systems; the checker lists every served role.
//
// Component and type-role fallbacks are scoped to `.ds` descendants (`<DSRoot>`): a canvas
// that names a local class `.card` without the system declaring it is never restyled.

import { scanCssRules } from './css-scan.ts';
import type { Registry } from './registry.ts';
import type { SystemModel } from './system.ts';

export interface Declared {
  /** custom-property names the system declares (counted rules, any theme) */
  names: ReadonlySet<string>;
  /** class names in the system's `_components.css` and tokens CSS selectors */
  classes: ReadonlySet<string>;
  rootClass?: string | null;
}

export function declaredBy(model: SystemModel): Declared {
  return {
    names: model.declared,
    classes: new Set([...model.componentClasses, ...model.tokensClasses]),
    rootClass: model.config.rootClass,
  };
}

const SUPPORTS_RELATIVE =
  '@supports not (color: oklch(from red clamp(0, (0.62 - l) * 1000, 1) 0 0))';

function classesIn(selector: string): string[] {
  return [...selector.matchAll(/\.(-?[A-Za-z_][A-Za-z0-9_-]*)/g)].map((m) => m[1]);
}

/** Prefix every selector of a rule list with `:where(.ds) ` (keeps rule text otherwise). */
function scopeToDs(css: string, keep: (classes: string[]) => boolean): string[] {
  const out: string[] = [];
  for (const r of scanCssRules(css)) {
    if (r.atRule || r.parent !== -1) continue;
    const classes = classesIn(r.selector);
    if (!keep(classes)) continue;
    const sel = r.selector
      .split(',')
      .map((s) => `:where(.ds) ${s.trim()}`)
      .join(', ');
    out.push(`${sel} {${css.slice(r.bodyStart, r.bodyEnd)}}`);
  }
  return out;
}

export function renderFallbacks(reg: Registry, declared?: Declared): string {
  const names = declared?.names ?? new Set<string>();
  const classes = declared?.classes ?? new Set<string>();
  const scope = [
    ':root',
    '.ds',
    ...(declared?.rootClass ? [`.${declared.rootClass}`] : []),
    '[data-theme]',
  ];
  const where = `:where(${scope.join(', ')})`;
  const roles = reg.roles.filter((r) => r.fallback !== null && !names.has(r.name));
  const lines: string[] = ['@layer maude.fallback;', '@layer maude.fallback {'];
  if (roles.length) {
    lines.push(`  ${where} {`);
    for (const r of roles) lines.push(`    ${r.name}: ${r.fallback};`);
    lines.push('  }');
  }
  const unsupported = roles.filter((r) => r.fallbackUnsupported);
  if (unsupported.length) {
    lines.push(`  ${SUPPORTS_RELATIVE} {`);
    lines.push(`    ${where} {`);
    for (const r of unsupported) lines.push(`      ${r.name}: ${r.fallbackUnsupported};`);
    lines.push('    }');
    lines.push('  }');
  }
  for (const t of reg.typeRoles) {
    if (t.whenSlot) continue; // display-N: per-slot, emitted below when the system has the slot
    if (classes.has(t.class)) continue;
    const decls = Object.entries(t.fallback).map(([p, v]) => `${p}: ${v};`);
    lines.push(`  :where(.ds) .${t.class} { ${decls.join(' ')} }`);
  }
  const display = reg.typeRoles.find((t) => t.whenSlot === 'display');
  if (display && declared) {
    const idxs = [...names]
      .map((n) => /^--display-(\d+)$/.exec(n)?.[1])
      .filter(Boolean)
      .map(Number)
      .sort((a, b) => a - b);
    for (const i of idxs) {
      const cls = `t-display-${i}`;
      if (classes.has(cls)) continue;
      const decls = Object.entries(display.fallback).map(
        ([p, v]) => `${p}: ${v.replace('--display-N', `--display-${i}`)};`
      );
      lines.push(`  :where(.ds) .${cls} { ${decls.join(' ')} }`);
    }
  }
  for (const c of reg.components.core) {
    if (!c.fallbackCss) continue;
    const rules = scopeToDs(c.fallbackCss, (cls) => !cls.some((x) => classes.has(x)));
    for (const r of rules) lines.push(`  ${r}`);
  }
  lines.push('}');
  return `${lines.join('\n')}\n`;
}

export const FALLBACKS_HEADER =
  '/* GENERATED by scripts/gen-ds-schema.mjs from apps/studio/schema/ds-schema-v1.json — DO NOT EDIT.\n' +
  ' * The full fallback layer (V2-1.13 §5.5). The canvas shell injects a per-system subset that\n' +
  ' * defines only the roles and classes that system never declares. */\n';
