// Fixture boards for the annotation E2E scenarios (v2 elements, canonical field names).

/** Like the user's report board: a section holding an ellipse + a rect joined by an arrow, plus loose sticky / text / rect. */
export const REPORT_BOARD = [
  { id: 'sec', type: 'section', index: 'a0', x: 100, y: 100, w: 820, h: 460, label: 'Section' },
  {
    id: 'circle',
    type: 'shape',
    parent: 'sec',
    index: 'a0',
    kind: 'ellipse',
    x: 80,
    y: 80,
    w: 160,
    h: 160,
    fill: '#e7e7e7',
    width: 3,
    label: { text: 'aads\nasda' },
  },
  {
    id: 'box',
    type: 'shape',
    parent: 'sec',
    index: 'a1',
    kind: 'rect',
    x: 520,
    y: 100,
    w: 160,
    h: 160,
    radius: 12,
    fill: '#e7e7e7',
    width: 3,
    label: { text: 'Ahoj' },
  },
  {
    id: 'link',
    type: 'arrow',
    parent: 'sec',
    index: 'a2',
    start: { el: 'circle' },
    end: { el: 'box' },
  },
  { id: 'note', type: 'sticky', index: 'a1', x: 1000, y: 100, w: 240, h: 240, text: 'Ahoj' },
  { id: 'label', type: 'text', index: 'a2', x: 1000, y: 420, w: 60, h: 17, text: 'Ahoj' },
  {
    id: 'lone',
    type: 'shape',
    index: 'a3',
    kind: 'rect',
    x: 1300,
    y: 100,
    w: 160,
    h: 120,
    fill: '#e7e7e7',
  },
  // Sits ON the canvas artboard (harness: artboard `a` at 700,700, 200×120).
  {
    id: 'onart',
    type: 'shape',
    index: 'a4',
    kind: 'rect',
    x: 720,
    y: 710,
    w: 120,
    h: 80,
    fill: '#fbe0e1',
    label: { text: 'Over' },
  },
  // A shape with no label yet (Milestone C: typing creates one).
  {
    id: 'plain',
    type: 'shape',
    index: 'a5',
    kind: 'rect',
    x: 1500,
    y: 420,
    w: 140,
    h: 100,
    fill: '#dfe7f7',
  },
  // Ink painted OVER the sticky: it must stay above the sticky's text (z-order).
  {
    id: 'ink',
    type: 'pen',
    index: 'a6',
    points: [1020, 180, 1120, 190, 1220, 185],
    color: '#c0392b',
    width: 6,
  },
];
