// perf-canvas.mjs — deterministic large-canvas fixture generator.
//
// Produces the synthetic worst-case the render-performance work is measured
// against: N artboards on one world plane plus M annotation stickies, with NO
// filters, blends or feTurbulence. That absence is the point — the earlier
// moodboard RCA (.ai/archive/logs/rca/issue-canvas-pan-zoom-jank-large-
// moodboard.md) covered the expensive-paint regime; the failures this fixture
// reproduces (a 128-artboard onboarding flow, a sticky-dense FigJam board) are
// the opposite shape: cheap paint, huge node count. Mixing filters back in
// would re-measure the case that is already fixed.
//
// Written as .mjs rather than the .ts the plan named, because the probe
// (`_perf-probe.mjs`) runs under plain node and imports this module directly;
// bun tests import .mjs identically, so nothing is lost.
//
// Deterministic by construction — no Date.now(), no Math.random(). Two runs
// produce byte-identical files, so a re-measured baseline compares like with
// like.

import { mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

// The mixed-board generator imports the canonical serializer from
// annotations-model.ts, so it is loaded lazily: the sticky-only path (and any
// plain-node importer of this module) never has to resolve a .ts file.
const MIXED_MODULE = './perf-annotations-mixed.mjs';

/** Grid geometry — mirrors DesignCanvas's own default grid vocabulary. */
const BOARD_W = 1280;
const BOARD_H = 800;
const GUTTER = 80;
const COLS = 8;

/** Sticky geometry, matching the imported-FigJam shape (240px square, r=8). */
const STICKY = 240;
const STICKY_GAP = 40;
const STICKY_COLS = 12;

// Fixed word pool — index-addressed, never shuffled, so labels stay stable
// across regenerations.
const WORDS = [
  'Onboarding',
  'Signup',
  'Paywall',
  'Empty state',
  'Error',
  'Success',
  'Profile',
  'Settings',
  'Search',
  'Detail',
  'Checkout',
  'Review',
];

const STICKY_TEXT = [
  'Ship the import path',
  'Cut the cold start',
  'Fewer modal steps',
  'Copy is too long',
  'Needs an empty state',
  'Great onboarding',
  'Slow on mobile',
  'Loved the polish',
];

/** Deterministic pseudo-shuffle: a fixed odd stride over the pool. */
function pick(pool, i) {
  return pool[(i * 7) % pool.length];
}

/**
 * Body markup for one artboard. Deliberately ~35 DOM nodes — a realistic mock,
 * not an empty box. An empty artboard would understate reconciliation cost and
 * flatter every measurement taken against this fixture.
 */
function artboardBody(i) {
  const rows = Array.from(
    { length: 6 },
    (_, r) => `
          <div style={{ display: 'flex', gap: 12, alignItems: 'center' }}>
            <div style={{ width: 32, height: 32, borderRadius: 6, background: 'var(--bg-2, #e8e3d8)' }} />
            <div style={{ flex: 1 }}>
              <div style={{ height: 10, width: '${40 + ((i + r) % 5) * 10}%', borderRadius: 3, background: 'var(--bg-3, #ddd6c8)' }} />
              <div style={{ height: 8, width: '${25 + ((i + r) % 4) * 8}%', marginTop: 6, borderRadius: 3, background: 'var(--bg-2, #e8e3d8)' }} />
            </div>
            <div style={{ width: 56, height: 24, borderRadius: 4, background: 'var(--accent, #6b5bd6)', opacity: 0.18 }} />
          </div>`
  ).join('');

  return `
        <div style={{ padding: 32, display: 'flex', flexDirection: 'column', gap: 16 }}>
          <h2 style={{ margin: 0, font: '600 24px/1.2 var(--font-sans, system-ui)' }}>${pick(WORDS, i)} ${i}</h2>
          <p style={{ margin: 0, font: '400 14px/1.5 var(--font-sans, system-ui)', opacity: 0.7 }}>
            Synthetic perf fixture board ${i} — no filters, no blends, cheap paint.
          </p>${rows}
        </div>`;
}

/** Build the canvas .tsx source for `boards` artboards. */
export function renderCanvasSource(boards) {
  const items = Array.from({ length: boards }, (_, i) => {
    const col = i % COLS;
    const row = Math.floor(i / COLS);
    const x = col * (BOARD_W + GUTTER);
    const y = row * (BOARD_H + GUTTER);
    return `      <DCArtboard
        id="b${i}"
        label="${pick(WORDS, i)} ${i}"
        width={${BOARD_W}}
        height={${BOARD_H}}
        x={${x}}
        y={${y}}
        fixed
      >${artboardBody(i)}
      </DCArtboard>`;
  }).join('\n');

  return `// GENERATED by apps/studio/test/fixtures/perf-canvas.mjs — do not hand-edit.
// Synthetic render-performance fixture: ${boards} artboards, no filters/blends.
import { DCArtboard, DesignCanvas } from '@maude/canvas-lib';

export default function Canvas() {
  return (
    <DesignCanvas>
${items}
    </DesignCanvas>
  );
}
`;
}

/** Build the `.meta.json` sidecar carrying the artboard grid positions. */
export function renderMeta(boards) {
  const artboards = Array.from({ length: boards }, (_, i) => ({
    id: `b${i}`,
    x: (i % COLS) * (BOARD_W + GUTTER),
    y: Math.floor(i / COLS) * (BOARD_H + GUTTER),
  }));
  return {
    title: `Perf fixture (${boards} boards)`,
    subtitle: 'Generated render-performance fixture — safe to delete.',
    tags: ['perf-fixture'],
    status: 'draft',
    layout: { artboards },
  };
}

/**
 * Build the annotations SVG carrying `strokes` stickies. Shape copied from a
 * real imported-FigJam board so the layer exercises the same code path
 * (`data-mdcc-annotations`, `data-tool="sticky"`, rect + body text per group).
 */
export function renderAnnotations(strokes) {
  if (strokes <= 0) return null;
  const nodes = Array.from({ length: strokes }, (_, i) => {
    const col = i % STICKY_COLS;
    const row = Math.floor(i / STICKY_COLS);
    const x = col * (STICKY + STICKY_GAP);
    // Park the sticky field below the artboard grid so the two layers are
    // measurable together without overlapping hit-test surfaces.
    const y = 100000 + row * (STICKY + STICKY_GAP);
    return (
      `<g data-id="perf_${i}" data-tool="sticky" data-r="8" data-fs="14" fill="#cfc4ec">` +
      `<rect x="${x}" y="${y}" width="${STICKY}" height="${STICKY}" rx="8" ry="8"/>` +
      `<text data-sticky-body="1" x="${x + 12}" y="${y + 12}" font-size="14" fill="#1a1a1a" dominant-baseline="hanging">` +
      `${pick(STICKY_TEXT, i)} ${i}</text></g>`
    );
  }).join('');
  return `<svg xmlns="http://www.w3.org/2000/svg" data-mdcc-annotations="1">${nodes}</svg>`;
}

/**
 * The annotations file name the dev-server actually reads for `ui/<slug>.tsx`.
 * Mirrors `canvasSlugFromRel` (canvas-slug.ts): `/`→`-`, whitespace→`_`,
 * lowercase — hyphens are KEPT. (This used to rewrite `-`→`_`, writing
 * `ui-perf_fixture.annotations.svg` while the server read
 * `ui-perf-fixture.annotations.svg`, so every "with annotations" run actually
 * measured an empty annotation layer.)
 */
export function annotationsFileName(slug) {
  // DDR-242 — the v2 board.
  return `ui-${slug.replace(/\s+/g, '_').toLowerCase()}.annotations.json`;
}

/** World origin of the mixed annotation field: just right of the artboard grid. */
export function mixedOrigin(boards) {
  const cols = Math.min(COLS, Math.max(1, boards));
  return { originX: cols * (BOARD_W + GUTTER) + 200, originY: 0 };
}

/**
 * Write the fixture into a design root.
 *
 * @param {object} opts
 * @param {string} opts.designRoot  Absolute path to a `.design/` directory.
 * @param {number} [opts.boards]    Artboard count (default 128 — the SPKIE repro).
 * @param {number} [opts.strokes]   Sticky count (default 150 — the Team Retro repro).
 *                                  With `mix`, the TOTAL mixed element count.
 * @param {boolean} [opts.mix]      Mixed board (all kinds, bound arrows, nested
 *                                  sections, groups — perf-annotations-mixed.mjs)
 *                                  placed in view beside the artboards, instead
 *                                  of the sticky-only field.
 * @param {string} [opts.slug]      Canvas basename (default `perf-fixture`).
 * @returns {Promise<{canvasPath: string, metaPath: string, annotationsPath: string|null, annotationsBytes: number, canvasRel: string}>}
 */
export async function writePerfCanvas({
  designRoot,
  boards = 128,
  strokes = 150,
  mix = false,
  slug = 'perf-fixture',
}) {
  const canvasPath = join(designRoot, 'ui', `${slug}.tsx`);
  const metaPath = join(designRoot, 'ui', `${slug}.meta.json`);
  mkdirSync(dirname(canvasPath), { recursive: true });

  writeFileSync(canvasPath, renderCanvasSource(boards), 'utf8');
  writeFileSync(metaPath, `${JSON.stringify(renderMeta(boards), null, 2)}\n`, 'utf8');

  // Annotations live at the design root under the flattened `<dir>-<slug>`
  // naming the annotations API uses, NOT beside the canvas.
  let annotationsPath = null;
  let annotationsBytes = 0;
  const svg = mix
    ? (await import(MIXED_MODULE)).renderMixedAnnotations(strokes, mixedOrigin(boards))
    : renderAnnotations(strokes);
  const annAbs = join(designRoot, annotationsFileName(slug));
  // A v1 board a previous run left would be quarantined next to the v2 one.
  rmSync(annAbs.replace(/\.json$/, '.svg'), { force: true });
  if (svg) {
    // The generators build v1 strokes; the board on disk is the v2 element
    // model, produced by the same migration a real legacy file goes through.
    const [{ migrateSvg }, { serializeBoard }] = await Promise.all([
      import('../../annotations/migrate-v1.ts'),
      import('../../annotations/schema.ts'),
    ]);
    const board = serializeBoard(migrateSvg(svg).elements);
    annotationsPath = annAbs;
    writeFileSync(annotationsPath, board, 'utf8');
    annotationsBytes = Buffer.byteLength(board, 'utf8');
  } else {
    // `--strokes 0` must measure an EMPTY layer, not whatever board a previous
    // run left behind under the same name.
    rmSync(annAbs, { force: true });
  }

  return { canvasPath, metaPath, annotationsPath, annotationsBytes, canvasRel: `ui/${slug}.tsx` };
}
