#!/usr/bin/env node
// Token pipeline (V2-2.6, T13 minimum) — every token copy the product ships is GENERATED from a
// design system's colors_and_type.css; nothing is typed by hand.
//
//   node scripts/gen-tokens.mjs           write both outputs
//   node scripts/gen-tokens.mjs --check   exit 1 on drift (part of the `tokens` quality gate)
//
// 1. apps/studio/client/styles/1-tokens-maude-v2.css — the maude-v2 ladder for the studio client,
//    scoped to `.maude-v2[data-theme]` ONLY: every `:root` is dropped from the source's selector
//    lists, so the v1 shell (which never carries `.maude-v2`) is untouched until Phase 4 mounts the
//    v2 chrome under that wrapper.
// 2. apps/studio/canvas-hud-tokens.gen.ts — the canvas iframe's HUD/chrome block
//    (`--maude-hud-*`, `--maude-chrome-*`) that canvas-shell.tsx injects. Filled from HUD_SOURCE_DS
//    through HUD_TEMPLATE below; `maude` today (byte-identical to the block it replaces), switched
//    to `maude-v2` by the Phase 4 shell work — change the constant and the name map, regenerate.
// (The site's copy, site/app/mdcc-tokens.css, has its own generator: site/scripts/sync-mdcc-tokens.mjs.)

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const CHECK = process.argv.includes('--check');
const ds = (name) => readFileSync(join(ROOT, `.design/system/${name}/colors_and_type.css`), 'utf8');

// ── 1 · maude-v2 → client, scoped ────────────────────────────────────────────────────────────
const V2_OUT = 'apps/studio/client/styles/1-tokens-maude-v2.css';
function scopedV2() {
  const src = ds('maude-v2');
  const lines = src.split('\n');
  const out = [];
  for (let i = 0; i < lines.length; i++) {
    const l = lines[i];
    if (/^\s*:root\s*\{/.test(l))
      throw new Error(
        'maude-v2 declares a bare `:root {` block — it cannot be scoped; add a .maude-v2 selector'
      );
    if (/^\s*:root,\s*$/.test(l)) {
      if (!/^\s*\.maude-v2\[data-theme="(light|dark)"\]/.test(lines[i + 1] ?? ''))
        throw new Error(
          `maude-v2 line ${i + 1}: \`:root,\` is not followed by a .maude-v2 selector`
        );
      continue; // drop :root from this selector list
    }
    out.push(l);
  }
  const body = out.join('\n').trim();
  return `/* GENERATED by scripts/gen-tokens.mjs from .design/system/maude-v2/colors_and_type.css
 * — DO NOT EDIT BY HAND. Run: node scripts/gen-tokens.mjs
 * Scoped to .maude-v2[data-theme] only (every :root dropped), so the v1 shell is untouched until
 * the v2 chrome mounts under that wrapper (Phase 4). */

@layer tokens {
${body
  .split('\n')
  .map((l) => (l ? `  ${l}` : l))
  .join('\n')}
}
`;
}

// ── 2 · HUD block for the canvas iframe ──────────────────────────────────────────────────────
const HUD_OUT = 'apps/studio/canvas-hud-tokens.gen.ts';
const HUD_SOURCE_DS = 'maude';
// Theme blocks of the source DS: the selector line that opens each block.
const HUD_BLOCKS = { dark: '.maude[data-theme="dark"] {', light: '.maude[data-theme="light"] {' };
// {dark:name} / {light:name} = that DS token's value in that theme's block.
const HUD_TEMPLATE = `
:root,
:root[data-maude-theme="dark"] {
  --maude-hud-accent:        {dark:accent};
  --maude-hud-accent-hover:  {dark:accent-hover};
  --maude-hud-accent-active: {dark:accent-active};
  --maude-hud-accent-fg:     {dark:accent-fg};
  --maude-hud-accent-tint:   color-mix(in oklab, {dark:accent} 16%, transparent);

  --maude-chrome-bg-0:      {dark:bg-0};
  --maude-chrome-bg-1:      {dark:bg-1};
  --maude-chrome-bg-2:      {dark:bg-2};
  --maude-chrome-fg-0:      {dark:fg-0};
  --maude-chrome-fg-1:      {dark:fg-1};
  --maude-chrome-border:    {dark:border-subtle};
  --maude-chrome-dot:       {dark:canvas-dot};
  --maude-chrome-shadow:    rgba(0, 0, 0, 0.46);
  --maude-chrome-font-mono: 'JetBrains Mono', 'Geist Mono', ui-monospace, 'SF Mono', Menlo, monospace;
}
:root[data-maude-theme="light"] {
  --maude-hud-accent:        {light:accent};
  --maude-hud-accent-hover:  {light:accent-hover};
  --maude-hud-accent-active: {light:accent-active};
  --maude-hud-accent-fg:     {light:accent-fg};
  --maude-hud-accent-tint:   color-mix(in oklab, {light:accent} 12%, transparent);

  --maude-chrome-bg-0:   {light:bg-0};
  --maude-chrome-bg-1:   {light:bg-1};
  --maude-chrome-bg-2:   {light:bg-2};
  --maude-chrome-fg-0:   {light:fg-0};
  --maude-chrome-fg-1:   {light:fg-1};
  --maude-chrome-border: {light:border-subtle};
  --maude-chrome-dot:    {light:canvas-dot};
  --maude-chrome-shadow: color-mix(in oklab, {light:fg-0} 14%, transparent);
}
`;

function blockOf(src, opener) {
  const at = src.indexOf(opener);
  if (at < 0) throw new Error(`${HUD_SOURCE_DS}: block "${opener}" not found`);
  return src.slice(at, src.indexOf('\n}', at));
}
function hudCss() {
  const src = ds(HUD_SOURCE_DS);
  const blocks = Object.fromEntries(
    Object.entries(HUD_BLOCKS).map(([t, o]) => [t, blockOf(src, o)])
  );
  return HUD_TEMPLATE.replace(/\{(dark|light):([a-z0-9-]+)\}/g, (_, theme, name) => {
    const m = blocks[theme].match(new RegExp(`^\\s*--${name}:\\s*([^;]+);`, 'm'));
    if (!m) throw new Error(`${HUD_SOURCE_DS} ${theme}: no --${name}`);
    return m[1].trim();
  });
}
function hudModule() {
  return `// GENERATED by scripts/gen-tokens.mjs from .design/system/${HUD_SOURCE_DS}/colors_and_type.css
// — DO NOT EDIT BY HAND. Run: node scripts/gen-tokens.mjs
// The canvas iframe's HUD/chrome token block (--maude-hud-*, --maude-chrome-*), injected by
// canvas-shell.tsx. See the comment above its import there for why the HUD owns its own family.
export const HUD_TOKENS_CSS = \`${hudCss()}\`;
`;
}

// ── write / check ────────────────────────────────────────────────────────────────────────────
const outputs = [
  [V2_OUT, scopedV2()],
  [HUD_OUT, hudModule()],
];
let drift = 0;
for (const [rel, text] of outputs) {
  const p = join(ROOT, rel);
  let cur = null;
  try {
    cur = readFileSync(p, 'utf8');
  } catch {
    /* missing */
  }
  if (CHECK) {
    if (cur !== text) {
      drift++;
      console.error(`[gen-tokens] DRIFT: ${rel} is stale — run: node scripts/gen-tokens.mjs`);
    }
  } else if (cur !== text) {
    writeFileSync(p, text);
    console.log(`[gen-tokens] wrote ${rel}`);
  }
}
if (CHECK) {
  if (drift) process.exit(1);
  console.log('[gen-tokens] in sync');
}
