#!/usr/bin/env node
// gen-actions.mjs — the action registry's generated files (Maude v2, V2-1.3 contract §5.1, §5.7;
// V2-2.4). The registry (apps/studio/actions/) is the source; these are derived and committed,
// drift-gated like site/lib/roadmap.json:
//
//   apps/studio/actions/keymap.gen.ts   the canvas iframe's slim key table (§5.7)
//
// Usage (repo root):
//   node scripts/gen-actions.mjs           write the files
//   node scripts/gen-actions.mjs --check   exit 1 when a committed file differs from the registry
//
// Output goes through Biome (the repo's formatter) so `pnpm lint` and the check agree byte for
// byte. Node 24 strips the registry's erasable TypeScript natively.

import { spawnSync } from 'node:child_process';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const CHECK = process.argv.includes('--check');

const { ACTIONS } = await import('../apps/studio/actions/index.ts');
const { bindingInDocument } = await import('../apps/studio/actions/documents.ts');

function die(msg) {
  console.error(`gen-actions: ${msg}`);
  process.exit(2);
}

/** Format `text` as Biome would format the file at `rel`. */
function biome(rel, text) {
  const r = spawnSync(
    join(ROOT, 'node_modules/.bin/biome'),
    ['format', `--stdin-file-path=${rel}`],
    {
      cwd: ROOT,
      input: text,
      encoding: 'utf8',
      maxBuffer: 32 * 1024 * 1024,
    }
  );
  if (r.status !== 0) die(`biome could not format ${rel}:\n${(r.stderr || r.stdout).slice(-1500)}`);
  return r.stdout;
}

// ── keymap.gen.ts: every binding the canvas document resolves, no labels or docs ──────────
function keymap() {
  const rows = [];
  for (const a of ACTIONS) {
    const keys = (a.keys ?? []).filter((b) => bindingInDocument(b, 'canvas'));
    if (!keys.length) continue;
    const row = { id: a.id, exec: a.exec };
    if (a.visible) row.visible = a.visible;
    if (a.enabled) row.enabled = a.enabled;
    if (a.fromCanvas) row.fromCanvas = true;
    row.keys = keys;
    rows.push(row);
  }
  return `// GENERATED by scripts/gen-actions.mjs from apps/studio/actions/ — DO NOT EDIT BY HAND.
// Run: node scripts/gen-actions.mjs (CI runs it with --check). The canvas iframe's slim key
// table (V2-1.3 §5.7): every binding the canvas document resolves, without labels or docs, so the
// canvas bundle never needs the whole registry and never waits for a keymap push.
import type { KeyedAction } from './types.ts';

export const CANVAS_KEYMAP: readonly KeyedAction[] = ${JSON.stringify(rows)};
`;
}

const OUTPUTS = [['apps/studio/actions/keymap.gen.ts', keymap()]];

let stale = 0;
for (const [rel, raw] of OUTPUTS) {
  const want = biome(rel, raw);
  const path = join(ROOT, rel);
  const have = existsSync(path) ? readFileSync(path, 'utf8') : null;
  if (CHECK) {
    if (have !== want) {
      stale++;
      console.error(
        `gen-actions: ${rel} is stale — run \`node scripts/gen-actions.mjs\` and commit it`
      );
    }
    continue;
  }
  if (have !== want) {
    writeFileSync(path, want);
    console.log(`wrote ${rel}`);
  } else console.log(`same  ${rel}`);
}
if (CHECK) {
  if (stale) process.exit(1);
  console.log(`gen-actions: ${OUTPUTS.length} generated file(s) match the registry`);
}
