// AUTO-GENERATED by draw-agent (maude-v2-patterns.build.ts) — JSX twin of patterns.svg (DDR-067).
export default function MaudeV2Patterns(props) {
  return (
    <svg {...props} viewBox="0 0 928 560" role="img">
      <title>maude-v2 patterns</title>
      <desc>Seamless decorative &lt;pattern&gt; tiles for the maude-v2 design system, light and dark: mv2-pattern-dots-&#123;light|dark&#125; (20px canvas dot grid, --canvas-dot), mv2-pattern-grain-&#123;light|dark&#125; (paper/frost grain for islands and onboarding, --fg-0 specks), mv2-pattern-confetti-&#123;light|dark&#125; (sparse rotated sticky squares in the --object-* palette, for empty states). Use with fill="url(#id)" on a rect over the theme background; all tiles use userSpaceOnUse and stay quiet enough for text on top.</desc>
      <defs>
        <pattern id="mv2-pattern-dots-light" width="20" height="20" patternUnits="userSpaceOnUse">
          <circle cx="10" cy="10" r="1" fill="#b8bfc4" />
        </pattern>
        <filter id="mv2-grain-noise-light" x="0" y="0" width="1" height="1" colorInterpolationFilters="sRGB">
          <feTurbulence type="fractalNoise" baseFrequency="0.85" numOctaves="2" seed="7" stitchTiles="stitch" result="n" />
          <feColorMatrix in="n" type="matrix" values="0 0 0 0 0.102 0 0 0 0 0.125 0 0 0 0 0.149 3 0 0 0 -1.2" />
        </filter>
        <pattern id="mv2-pattern-grain-light" width="128" height="128" patternUnits="userSpaceOnUse">
          <g opacity="0.07" filter="url(#mv2-grain-noise-light)">
            <rect x="0" y="0" width="128" height="128" fill="#000000" />
          </g>
        </pattern>
        <pattern id="mv2-pattern-confetti-light" width="320" height="240" patternUnits="userSpaceOnUse">
          <g opacity="1">
            <g transform="translate(204.8 153.6) rotate(24)">
              <rect x="-4" y="-4" width="8" height="8" rx="1" fill="#ffb1a1" />
            </g>
            <g transform="translate(80 60) rotate(-16)">
              <rect x="-3" y="-3" width="6" height="6" rx="1" fill="#9ed7f3" />
            </g>
            <g transform="translate(0 180) rotate(34)">
              <rect x="-3" y="-3" width="6" height="6" rx="1" fill="#86db9d" />
            </g>
            <g transform="translate(320 180) rotate(34)">
              <rect x="-3" y="-3" width="6" height="6" rx="1" fill="#86db9d" />
            </g>
            <g transform="translate(160 0) rotate(-10)">
              <rect x="-2" y="-2" width="4" height="4" rx="1" fill="#cebdf2" />
            </g>
            <g transform="translate(160 240) rotate(-10)">
              <rect x="-2" y="-2" width="4" height="4" rx="1" fill="#cebdf2" />
            </g>
            <g transform="translate(240 80) rotate(-28)">
              <rect x="-2" y="-2" width="4" height="4" rx="1" fill="#fae180" />
            </g>
          </g>
        </pattern>
        <pattern id="mv2-pattern-dots-dark" width="20" height="20" patternUnits="userSpaceOnUse">
          <circle cx="10" cy="10" r="1" fill="#3a3d41" />
        </pattern>
        <filter id="mv2-grain-noise-dark" x="0" y="0" width="1" height="1" colorInterpolationFilters="sRGB">
          <feTurbulence type="fractalNoise" baseFrequency="0.85" numOctaves="2" seed="7" stitchTiles="stitch" result="n" />
          <feColorMatrix in="n" type="matrix" values="0 0 0 0 0.945 0 0 0 0 0.957 0 0 0 0 0.965 3 0 0 0 -1.2" />
        </filter>
        <pattern id="mv2-pattern-grain-dark" width="128" height="128" patternUnits="userSpaceOnUse">
          <g opacity="0.08" filter="url(#mv2-grain-noise-dark)">
            <rect x="0" y="0" width="128" height="128" fill="#000000" />
          </g>
        </pattern>
        <pattern id="mv2-pattern-confetti-dark" width="320" height="240" patternUnits="userSpaceOnUse">
          <g opacity="1">
            <g transform="translate(204.8 153.6) rotate(24)">
              <rect x="-4" y="-4" width="8" height="8" rx="1" fill="#803a2e" />
            </g>
            <g transform="translate(80 60) rotate(-16)">
              <rect x="-3" y="-3" width="6" height="6" rx="1" fill="#135a76" />
            </g>
            <g transform="translate(0 180) rotate(34)">
              <rect x="-3" y="-3" width="6" height="6" rx="1" fill="#0d6332" />
            </g>
            <g transform="translate(320 180) rotate(34)">
              <rect x="-3" y="-3" width="6" height="6" rx="1" fill="#0d6332" />
            </g>
            <g transform="translate(160 0) rotate(-10)">
              <rect x="-2" y="-2" width="4" height="4" rx="1" fill="#594878" />
            </g>
            <g transform="translate(160 240) rotate(-10)">
              <rect x="-2" y="-2" width="4" height="4" rx="1" fill="#594878" />
            </g>
            <g transform="translate(240 80) rotate(-28)">
              <rect x="-2" y="-2" width="4" height="4" rx="1" fill="#685000" />
            </g>
          </g>
        </pattern>
      </defs>
      <rect x="16" y="16" width="288" height="256" rx="20" fill="#f5f8fb" />
      <rect x="16" y="16" width="288" height="256" rx="20" fill="url(#mv2-pattern-dots-light)" />
      <text x="32" y="256" fontSize="12" fontFamily="-apple-system, system-ui, &quot;SF Pro Text&quot;, Inter, &quot;Segoe UI&quot;, sans-serif" fontWeight="600" fill="#1a2026">Canvas dot grid · 20 px</text>
      <rect x="320" y="16" width="288" height="256" rx="20" fill="#fcfeff" />
      <rect x="320" y="16" width="288" height="256" rx="20" fill="url(#mv2-pattern-grain-light)" />
      <text x="336" y="256" fontSize="12" fontFamily="-apple-system, system-ui, &quot;SF Pro Text&quot;, Inter, &quot;Segoe UI&quot;, sans-serif" fontWeight="600" fill="#1a2026">Frost grain · islands, onboarding</text>
      <rect x="624" y="16" width="288" height="256" rx="20" fill="#f5f8fb" />
      <rect x="624" y="16" width="288" height="256" rx="20" fill="url(#mv2-pattern-confetti-light)" />
      <text x="640" y="256" fontSize="12" fontFamily="-apple-system, system-ui, &quot;SF Pro Text&quot;, Inter, &quot;Segoe UI&quot;, sans-serif" fontWeight="600" fill="#1a2026">Sticky confetti · empty states</text>
      <rect x="16" y="288" width="288" height="256" rx="20" fill="#15171a" />
      <rect x="16" y="288" width="288" height="256" rx="20" fill="url(#mv2-pattern-dots-dark)" />
      <text x="32" y="528" fontSize="12" fontFamily="-apple-system, system-ui, &quot;SF Pro Text&quot;, Inter, &quot;Segoe UI&quot;, sans-serif" fontWeight="600" fill="#f1f4f6">Canvas dot grid · 20 px</text>
      <rect x="320" y="288" width="288" height="256" rx="20" fill="#1e2124" />
      <rect x="320" y="288" width="288" height="256" rx="20" fill="url(#mv2-pattern-grain-dark)" />
      <text x="336" y="528" fontSize="12" fontFamily="-apple-system, system-ui, &quot;SF Pro Text&quot;, Inter, &quot;Segoe UI&quot;, sans-serif" fontWeight="600" fill="#f1f4f6">Frost grain · islands, onboarding</text>
      <rect x="624" y="288" width="288" height="256" rx="20" fill="#15171a" />
      <rect x="624" y="288" width="288" height="256" rx="20" fill="url(#mv2-pattern-confetti-dark)" />
      <text x="640" y="528" fontSize="12" fontFamily="-apple-system, system-ui, &quot;SF Pro Text&quot;, Inter, &quot;Segoe UI&quot;, sans-serif" fontWeight="600" fill="#f1f4f6">Sticky confetti · empty states</text>
    </svg>
  );
}
