// AI is ready — generated by draw-agent (maude-v2 spot art)
<svg viewBox="0 0 240 160" aria-hidden="true">
  <g>
    <circle cx="88" cy="40" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="104" cy="40" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="120" cy="40" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="136" cy="40" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="152" cy="40" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="56" cy="56" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="72" cy="56" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="88" cy="56" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="104" cy="56" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="120" cy="56" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="136" cy="56" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="152" cy="56" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="168" cy="56" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="184" cy="56" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="56" cy="72" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="72" cy="72" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="88" cy="72" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="104" cy="72" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="120" cy="72" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="136" cy="72" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="152" cy="72" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="168" cy="72" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="184" cy="72" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="56" cy="88" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="72" cy="88" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="88" cy="88" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="104" cy="88" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="120" cy="88" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="136" cy="88" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="152" cy="88" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="168" cy="88" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="184" cy="88" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="56" cy="104" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="72" cy="104" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="88" cy="104" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="104" cy="104" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="120" cy="104" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="136" cy="104" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="152" cy="104" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="168" cy="104" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="184" cy="104" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="88" cy="120" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="104" cy="120" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="120" cy="120" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="136" cy="120" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="152" cy="120" r="1" fill="var(--canvas-dot, #b8bfc4)" />
  </g>
  <g opacity="0.6">
    <circle cx="72" cy="24" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="88" cy="24" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="104" cy="24" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="120" cy="24" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="136" cy="24" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="152" cy="24" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="168" cy="24" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="40" cy="40" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="56" cy="40" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="72" cy="40" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="168" cy="40" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="184" cy="40" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="200" cy="40" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="40" cy="56" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="200" cy="56" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="24" cy="72" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="40" cy="72" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="200" cy="72" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="216" cy="72" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="24" cy="88" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="40" cy="88" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="200" cy="88" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="216" cy="88" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="40" cy="104" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="200" cy="104" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="40" cy="120" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="56" cy="120" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="72" cy="120" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="168" cy="120" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="184" cy="120" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="200" cy="120" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="72" cy="136" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="88" cy="136" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="104" cy="136" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="120" cy="136" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="136" cy="136" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="152" cy="136" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="168" cy="136" r="1" fill="var(--canvas-dot, #b8bfc4)" />
  </g>
  <g opacity="0.3">
    <circle cx="72" cy="8" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="88" cy="8" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="104" cy="8" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="120" cy="8" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="136" cy="8" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="152" cy="8" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="168" cy="8" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="40" cy="24" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="56" cy="24" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="184" cy="24" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="200" cy="24" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="24" cy="40" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="216" cy="40" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="8" cy="56" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="24" cy="56" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="216" cy="56" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="232" cy="56" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="8" cy="72" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="232" cy="72" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="8" cy="88" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="232" cy="88" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="8" cy="104" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="24" cy="104" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="216" cy="104" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="232" cy="104" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="24" cy="120" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="216" cy="120" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="40" cy="136" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="56" cy="136" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="184" cy="136" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="200" cy="136" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="72" cy="152" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="88" cy="152" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="104" cy="152" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="120" cy="152" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="136" cy="152" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="152" cy="152" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="168" cy="152" r="1" fill="var(--canvas-dot, #b8bfc4)" />
  </g>
  <g transform="translate(136 56) rotate(4 28 28)">
    <rect x="0" y="2" width="56" height="56" rx="4" fill="var(--object-ink, #1a2026)" opacity="0.08" />
    <rect x="0" y="0" width="56" height="56" rx="4" fill="var(--object-yellow, #fae180)" stroke="var(--fg-2, #6d7277)" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
    <line x1="11.2" y1="7.2" x2="11.2" y2="19.2" stroke="var(--spark, #f3572a)" strokeWidth="1.5" strokeLinecap="round" />
  </g>
  <polygon points="84,43 92.4,67.6 117,76 92.4,84.4 84,109 75.6,84.4 51,76 75.6,67.6" fill="var(--spark, #f3572a)" />
  <polygon points="128,26.1 130.52,33.48 137.9,36 130.52,38.52 128,45.9 125.48,38.52 118.1,36 125.48,33.48" fill="var(--spark, #f3572a)" />
</svg>
