// empty canvas — generated by draw-agent (maude-v2 spot art)
<svg viewBox="0 0 240 160" aria-hidden="true">
  <g>
    <circle cx="88" cy="40" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="104" cy="40" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="120" cy="40" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="136" cy="40" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="152" cy="40" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="56" cy="56" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="72" cy="56" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="88" cy="56" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="104" cy="56" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="120" cy="56" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="136" cy="56" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="152" cy="56" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="168" cy="56" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="184" cy="56" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="56" cy="72" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="72" cy="72" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="88" cy="72" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="104" cy="72" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="120" cy="72" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="136" cy="72" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="152" cy="72" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="168" cy="72" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="184" cy="72" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="56" cy="88" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="72" cy="88" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="88" cy="88" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="104" cy="88" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="120" cy="88" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="136" cy="88" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="152" cy="88" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="168" cy="88" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="184" cy="88" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="56" cy="104" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="72" cy="104" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="88" cy="104" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="104" cy="104" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="120" cy="104" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="136" cy="104" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="152" cy="104" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="168" cy="104" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="184" cy="104" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="88" cy="120" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="104" cy="120" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="120" cy="120" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="136" cy="120" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="152" cy="120" r="1" fill="var(--canvas-dot, #b8bfc4)" />
  </g>
  <g opacity="0.6">
    <circle cx="72" cy="24" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="88" cy="24" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="104" cy="24" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="120" cy="24" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="136" cy="24" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="152" cy="24" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="168" cy="24" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="40" cy="40" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="56" cy="40" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="72" cy="40" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="168" cy="40" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="184" cy="40" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="200" cy="40" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="40" cy="56" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="200" cy="56" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="24" cy="72" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="40" cy="72" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="200" cy="72" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="216" cy="72" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="24" cy="88" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="40" cy="88" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="200" cy="88" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="216" cy="88" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="40" cy="104" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="200" cy="104" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="40" cy="120" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="56" cy="120" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="72" cy="120" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="168" cy="120" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="184" cy="120" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="200" cy="120" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="72" cy="136" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="88" cy="136" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="104" cy="136" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="120" cy="136" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="136" cy="136" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="152" cy="136" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="168" cy="136" r="1" fill="var(--canvas-dot, #b8bfc4)" />
  </g>
  <g opacity="0.3">
    <circle cx="72" cy="8" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="88" cy="8" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="104" cy="8" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="120" cy="8" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="136" cy="8" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="152" cy="8" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="168" cy="8" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="40" cy="24" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="56" cy="24" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="184" cy="24" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="200" cy="24" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="24" cy="40" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="216" cy="40" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="8" cy="56" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="24" cy="56" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="216" cy="56" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="232" cy="56" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="8" cy="72" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="232" cy="72" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="8" cy="88" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="232" cy="88" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="8" cy="104" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="24" cy="104" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="216" cy="104" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="232" cy="104" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="24" cy="120" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="216" cy="120" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="40" cy="136" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="56" cy="136" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="184" cy="136" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="200" cy="136" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="72" cy="152" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="88" cy="152" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="104" cy="152" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="120" cy="152" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="136" cy="152" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="152" cy="152" r="1" fill="var(--canvas-dot, #b8bfc4)" />
    <circle cx="168" cy="152" r="1" fill="var(--canvas-dot, #b8bfc4)" />
  </g>
  <g transform="translate(116 20)">
    <rect x="0" y="2" width="96" height="72" rx="8" fill="var(--object-ink, #1a2026)" opacity="0.08" />
    <rect x="0" y="0" width="96" height="72" rx="8" fill="var(--bg-1, #fcfeff)" stroke="var(--fg-2, #6d7277)" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
    <line x1="4" y1="-8" x2="28" y2="-8" stroke="var(--fg-2, #6d7277)" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" opacity="0.55" />
  </g>
  <g transform="translate(36 96) rotate(-6 20 20)">
    <rect x="0" y="2" width="40" height="40" rx="4" fill="var(--object-ink, #1a2026)" opacity="0.08" />
    <rect x="0" y="0" width="40" height="40" rx="4" fill="var(--object-yellow, #fae180)" stroke="var(--fg-2, #6d7277)" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
    <line x1="8" y1="8" x2="32" y2="8" stroke="var(--object-ink, #1a2026)" strokeWidth="1.5" strokeLinecap="round" opacity="0.35" />
    <line x1="8" y1="14" x2="22.4" y2="14" stroke="var(--object-ink, #1a2026)" strokeWidth="1.5" strokeLinecap="round" opacity="0.35" />
  </g>
  <g transform="translate(100 76) rotate(5 18 18)">
    <rect x="0" y="2" width="36" height="36" rx="4" fill="var(--object-ink, #1a2026)" opacity="0.08" />
    <rect x="0" y="0" width="36" height="36" rx="4" fill="var(--object-lilac, #cebdf2)" stroke="var(--fg-2, #6d7277)" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
    <line x1="7.2" y1="7.2" x2="28.8" y2="7.2" stroke="var(--object-ink, #1a2026)" strokeWidth="1.5" strokeLinecap="round" opacity="0.35" />
    <line x1="7.2" y1="13.2" x2="20.16" y2="13.2" stroke="var(--object-ink, #1a2026)" strokeWidth="1.5" strokeLinecap="round" opacity="0.35" />
  </g>
  <g transform="translate(184 116) rotate(-3 14 14)">
    <rect x="0" y="2" width="28" height="28" rx="4" fill="var(--object-ink, #1a2026)" opacity="0.08" />
    <rect x="0" y="0" width="28" height="28" rx="4" fill="var(--object-green, #86db9d)" stroke="var(--fg-2, #6d7277)" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
    <line x1="5.6" y1="5.6" x2="22.4" y2="5.6" stroke="var(--object-ink, #1a2026)" strokeWidth="1.5" strokeLinecap="round" opacity="0.35" />
  </g>
</svg>
