# {{project_label}} — Design System

> **Philosophy layer.** This file documents the *why* and *what* of the design system. The *how* (tokens, specimens) lives in `colors_and_type.css` and the `preview/` directory.

## Purpose

{{purpose_one_liner}}

## Audience profile

- **Primary user:** {{audience_summary}}
- **Platforms:** {{platforms_summary}}
- **Default theme:** {{theme_default}}
- **Content tone:** {{content_tone}}

## Mood references

{{mood_references_block}}

## Foundations

### Token contract

All visuals reference `var(--*)` tokens declared in `colors_and_type.css`. Adding a new visual concept means **extending the tokens CSS first**, never inventing values inline in a canvas.

{{color_space_block}}

### Accent strategy

{{accent_rules_block}}

### Active token families

{{active_families_block}}

## Hard rules (non-negotiable)

- **Accessibility:** WCAG 2.1 AA contrast at every theme. Focus-visible always rendered. `prefers-reduced-motion: reduce` respected.
- **Touch targets:** {{touch_target_rule}}
- **No off-token values** in canvases. Extend tokens; don't inline.
- **No placeholder copy.** Real product strings only — no "Lorem Solutions Inc.", no "Click here".
- **Type ladder:** {{type_scale_summary}}
- **Motion:** every animation uses a `var(--dur-*)` and `var(--ease-*)` token. No magic numbers.

{{platform_hard_rules}}

## Voice & tone

{{voice_tone_block}}

## Iconography

{{iconography_summary}}

## Hard-stops the completeness-critic enforces

- Core tokens present (`--accent`, `--bg-0..4`, `--fg-0..3`, `--dur-flip`)
- Accent family count matches the declared strategy ({{accent_strategy_summary}})
- Color space matches the declared choice ({{color_space_summary}})
- `system/{{ds_dirname}}/preview/` populated with at least 8 specimens
- `colors_and_type.css` linked from every specimen
- `prefers-reduced-motion: reduce` guard present in tokens CSS

See `plugins/design/agents/design-system-completeness-critic.md` for the full rule set.

## Where things live

- **Tokens:** `colors_and_type.css` (this directory)
- **Specimens:** `preview/` (one HTML file per token family / component class)
- **UI kits:** `ui_kits/<platform>/` (reference compositions for {{platforms_summary}})
- **Brand assets:** `assets/logos/`, `assets/glyphs/`

## How to extend

1. Identify the missing concept (new component, new state, new platform).
2. **Extend `colors_and_type.css`** with any new tokens needed.
3. **Add a specimen** under `preview/` with a SPECIMEN comment header so future agents learn from it.
4. Run `/design:critic --system-only` to confirm completeness.
5. Commit.

Never extend the system by inventing values inline in a canvas — that's how systems decay.

## Token usage guide

<!-- ds-schema:token-guide:begin — GENERATED by scripts/gen-ds-schema.mjs from the schema registry, do not edit -->
One token, one job. A canvas uses these names only — never a literal colour, size or font.

| Token | Use it for |
| --- | --- |
| `--bg-0` | page / canvas surface (deepest) |
| `--bg-1` | card / panel body |
| `--bg-2` | popover, menu, sheet |
| `--bg-3` | input well, row hover |
| `--bg-4` | pressed / selected without accent |
| `--fg-0` | primary text |
| `--fg-1` | secondary text |
| `--fg-2` | tertiary text, meta |
| `--fg-3` | disabled text, non-text ornament |
| `--border-subtle` | hairline between related surfaces |
| `--border-default` | default control / card border |
| `--border-strong` | emphasised border, dividers that must read |
| `--accent` | the action fill: primary button, current selection |
| `--accent-hover` | action fill on hover |
| `--accent-active` | action fill while pressed |
| `--accent-fg` | text and icons on the action fill |
| `--accent-soft` | tinted background: chip, selected row |
| `--accent-on-soft` | text on --accent-soft |
| `--accent-text` | accent used as text or link on --bg-0..2 |
| `--status-success` | success fill and icon |
| `--status-warn` | warn fill and icon |
| `--status-error` | error fill and icon |
| `--status-info` | info fill and icon |
| `--status-success-fg` | text and icons on the success fill |
| `--status-warn-fg` | text and icons on the warn fill |
| `--status-error-fg` | text and icons on the error fill |
| `--status-info-fg` | text and icons on the info fill |
| `--status-success-soft` | tinted success background |
| `--status-warn-soft` | tinted warn background |
| `--status-error-soft` | tinted error background |
| `--status-info-soft` | tinted info background |
| `--status-success-text` | success used as text on surfaces |
| `--status-warn-text` | warn used as text on surfaces |
| `--status-error-text` | error used as text on surfaces |
| `--status-info-text` | info used as text on surfaces |
| `--presence-online` | collaborator online dot |
| `--presence-away` | collaborator away dot |
| `--presence-offline` | collaborator offline dot |
| `--shadow-sm` | low elevation: controls, chips |
| `--shadow-md` | mid elevation: cards, popovers |
| `--shadow-lg` | high elevation: dialogs, sheets |
| `--radius-xs` | smallest corner: chips, tags |
| `--radius-sm` | small controls |
| `--radius-md` | default control corner |
| `--radius-lg` | cards, panels |
| `--radius-xl` | sheets, large islands |
| `--radius-pill` | fully rounded |
| `--space-0` | spacing step 0 of the ordinal ladder |
| `--space-1` | spacing step 1 of the ordinal ladder |
| `--space-2` | spacing step 2 of the ordinal ladder |
| `--space-3` | spacing step 3 of the ordinal ladder |
| `--space-4` | spacing step 4 of the ordinal ladder |
| `--space-5` | spacing step 5 of the ordinal ladder |
| `--space-6` | spacing step 6 of the ordinal ladder |
| `--space-7` | spacing step 7 of the ordinal ladder |
| `--space-8` | spacing step 8 of the ordinal ladder |
| `--font-display` | headings and display text |
| `--font-body` | running text and UI labels |
| `--font-mono` | code, numbers in fields |
| `--type-xs` | font size, step xs |
| `--type-sm` | font size, step sm |
| `--type-base` | font size, step base |
| `--type-md` | font size, step md |
| `--type-lg` | font size, step lg |
| `--type-xl` | font size, step xl |
| `--type-2xl` | font size, step 2xl |
| `--type-3xl` | font size, step 3xl |
| `--lh-xs` | line height paired with --type-xs |
| `--lh-sm` | line height paired with --type-sm |
| `--lh-base` | line height paired with --type-base |
| `--lh-md` | line height paired with --type-md |
| `--lh-lg` | line height paired with --type-lg |
| `--lh-xl` | line height paired with --type-xl |
| `--lh-2xl` | line height paired with --type-2xl |
| `--lh-3xl` | line height paired with --type-3xl |
| `--dur-flip` | hover, press, toggle |
| `--dur-soft` | fades, tooltips |
| `--dur-panel` | panel open / collapse |
| `--dur-route` | route or canvas change |
| `--ease-out` | default curve for entering motion |
| `--ease-in-out` | curve for moving between two states |
| `--layout-max-w` | maximum content width (none = full bleed) |
| `--layout-gutter` | page side gutter |
| `--focus-ring` | keyboard focus outline colour (a colour, never a shadow) |
| `--focus-ring-width` | focus outline width |
| `--focus-ring-offset` | focus outline offset |
| `--selection` | text and object selection fill |
| `--scrim` | modal / sheet backdrop |
| `--weight-regular` | regular font weight |
| `--weight-medium` | medium font weight |
| `--weight-semibold` | semibold font weight |
| `--weight-bold` | the system's strongest weight (may equal semibold) |
| `--tracking-tight` | tight letter spacing |
| `--tracking-normal` | normal letter spacing |
| `--tracking-wide` | wide letter spacing |
<!-- ds-schema:token-guide:end -->
